"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
import Navbar from "@/components/layouts/Navbar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const disableNavbar = ["/auth/login", "/auth/register"];
  const pathName = usePathname();

  return (
    <SessionProvider>
      <html lang="en">
        <body className={inter.className}>
          {!disableNavbar.includes(pathName) && <Navbar />}
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
